// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtmujcqatktynybbubol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0bXVqY3FhdGt0eW55YmJ1Ym9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjU4MDEsImV4cCI6MjA3MDc0MTgwMX0.KJvBmF0mI19IRDWCDdAri9XO1wVUQPhxQsTMdznt2fw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});